### PR TITLE
Typo in eigK

### PR DESCRIPTION
**Pull request by Jarmill**
I think there's a typo in eigK.m in line 78:

li(li+1:li+nl) should be lab(li+1:lab+nl)

li is a counter, doesn't make sense for li to be indexed. Causes indexing errors in Matlab.

Jared

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you for the PR. This is the fix suggested in #18 .  What stopped me from applying this change is that I have never encountered this problem myself.  Could you post a small example that triggers the indexing problem?  Then I am very happy to pull your PR.

**Comment by Jarmill** [comment]
The attached SDP triggers this issue.

Jared

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by siko1056** [comment]
Dear Jared,

Please do not answer to the email notification you receive from GitHub directly by your email client.  This way I received no attachments.  Can you reply on GitHub (https://github.com/sqlp/sedumi/pull/54) instead?

Many thanks,
Kai

**Comment by Jarmill** [comment]
Kai,

GitHub wouldn’t allow me to attach a mat file.

A sharing link is here:
https://www.dropbox.com/s/r1adtxoechz2nom/lab_78.mat?dl=0

Please let me know if it works for you.

Jared

**Comment by siko1056** [comment]
I think this change is valid.

The function `eigK()` is only called here


https://github.com/sqlp/sedumi/blob/9289d8283cdf149818b74c46fc1ea6010f001457/eigK.m#L64-L68

**Comment by Jarmill** [comment]
The SDP lab_78 arose from a polynomial optimization problem: Yalmip to
SparsePOP to Sedumi. I don’t know if Yalmip models will call this routine,
but it’s interesting that Johan made the initial commit.

Jared

**Comment by siko1056** [comment]
I just attached your example wrapped in a ZIP file for future reference: 

[lab_78.mat.zip](https://github.com/sqlp/sedumi/files/4532390/lab_78.mat.zip)

This PR can be applied safely.

**Comment by johanlofberg** [comment]
FYI, my initial commit was simply the initial commit of the whole sedumi project, I take no responsibility for the code :-)

**Comment by siko1056** [comment]
@johanlofberg I am very sorry, if my point was not clear.  I do not want to blame anyone :innocent:   Of course you just committed SeDuMi as is.  In this initial commit state, I think it is more obvious, what that line of code was intended to do.  This idea is harder to get in later versions.

**Comment by johanlofberg** [comment]
Just kidding answering Jared

**Pull request merged**
