### PR TITLE
Improved dense A handling (pretransfo branch)

### PR DESCRIPTION
**Pull request by scholnik**
Here are some changes to improve the computational efficiency of sedumi when A is dense or has dense rows.  While matlab's dense linear algebra is well optimized and multithreaded, its sparse routines are single-threaded and considerably slower.  This creates bottlenecks when A is dense but stored as sparse.  (On my computer A'*A is faster using a dense representation for nonzero densities greater than about 0.05 or so.)  Some changes affect only LP/SOCP and are skipped if SDP blocks are given, while others are universal.  Several sparsity tolerances were added to pars to allow for tweaks to the sparse/dense heuristic.  These changes primarily seem to benefit either fully dense problems or problems with significant dense portions posed in the dual form.

I'm new to git and github, so bear with me.

### CODE REVIEW

**Comment by mcg1969** [comment]
@scholnik have you been using this branch much? It looks good to me, and I am inclined to merge it into pretransfo, with the goal of merging that into master.

**Comment by mcg1969** [comment]
Actually, reading through the comments more it seems clear we shouldn't hurry.

**Comment by scholnik** [comment]
This is the version I've been using since the discussion trailed off in 2014.  I don't think I've run into any further issues, although I probably wouldn't since my problems are automatically generated and don't use SDP at all.

**Comment by siko1056** [comment]
Three years passed, and I think no one will/can go further into this.  Some of the ideas should be followed, but maybe with smaller sized PRs and an example code to verify the improvment.

**Comment by scholnik** [comment]
I really don't remember the details anymore, but from the thread above it appears I did push some examples.  It still works great for me and is still faster for my problems than the main branch, but I seem to be the only one benefiting so I'm not sure it's worth following up.

**Pull request closed without merging**
