### PR TITLE
pretransfo branch rebase

### PR DESCRIPTION
**Pull request by mcg1969**
This is a PR that encapsulates the changes in the pretransfo branch into a single squashed commit. Octave binaries have also been removed.

### CODE REVIEW

**Comment by mcg1969** [comment]
Rebased again to get the latest mex files.

**Comment by siko1056** [comment]
@mcg1969 Does this PR have any chance to get merged?

**Comment by mcg1969** [comment]
I am more than happy to see this merged. My only concern is that we just don't have a solid testing infrastructure, so our users will be our CI system :-)

**Comment by siko1056** [comment]
I reviewed your changes (rebasing after such a long time is annoying) and it should now be save to merge the branch.

The new Travis CI checks say that for Linux Octave 4.0.0, 4.2.2, and macOS Octave 5.1.0 Homebrew there is no problem.

Manually I checked, that all five examples are working with Linux Octave 5.1.0 and Matlab R2019a; MS Windows Octave 5.1.0 and Matlab R2019b.

Thus please have the honor to finally merge your PR after 7 years, if you feel fine with it :wink:

**Comment by mcg1969** [comment]
You are fantastic! Thank you.

**Pull request merged**
