### PR TITLE
New VC2015 Windows builds. Also deleted o_win directory which we should not be supporting.

### PR DESCRIPTION
**Pull request by tholden**
I updated the Windows builds for my own use, so I'm again sharing them here.
Since OptiToolbox now uses VC2015 for builds, by rebuilding this with VC2015 I can save my users having to install additional MS redistributables.

### CODE REVIEW

**Comment by mcg1969** [comment]
@johanlofberg I'm just now getting around to seeing this. I think it's a safe merge. Do you agree?

**Comment by johanlofberg** [comment]
No idea, not confident enough when it comes to compilations etc.

**Comment by mcg1969** [comment]
Fair enough. I need to confirm that these files work with sufficiently older versions of Matlab.

**Comment by mcg1969** [comment]
(My general rule is to go back five years, which coincidentally puts us at Matlab 8.0 now.)

**Comment by siko1056** [comment]
After several years, I think to close this PR. The present old mex files did a great job for many years and systems. To avoid breaking working stuff, we should just keep them.

Currently I ensure that newer versions of Matlab and Octave can build own versions of the mex files without trouble.

@tholden This would mean to ensure mex is working on your customer's systems.  Do the present mex files do now work for you?  In MS Windows R2019b the present ones run without trouble.

**Pull request closed without merging**
